spring:
  application:
    name: item-service
    version: @project.version@
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configserver:"
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: UTC
  cloud:
    config:
      allow-override: true
      override-none: true
  jpa:
    properties:
      hibernate:
        dialect: ${database.dialect:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: validate 

server:
  port: 8080

logging:
  level:
    com.example.itemservice: DEBUG
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.springframework.cloud: DEBUG
    org.hibernate.validator: WARN
    com.example.itemservice.config.ConfigServerConnectionMonitor: INFO
    org.springframework.orm.jpa: WARN
    org.hibernate: WARN
    org.springframework.boot.autoconfigure.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: logs
  json-content:
    enabled: true
  http:
    enabled: true

config:
  polling:
    enabled: true
    interval: 30000

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true

spring.web.resources.add-mappings: false