spring:
  application:
    name: item-service
    version: @project.version@
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configserver:"
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: UTC
  cloud:
    config:
      allow-override: true
      override-none: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 1.5
        max-attempts: 12
  jpa:
    properties:
      hibernate:
        # dialect: ${database.dialect:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: validate 

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.itemservice: DEBUG
    org.hibernate.orm.deprecation: ERROR
    org.springframework.web.HttpLogging: INFO
    org.springframework.cloud.config: INFO
    org.springframework.cloud.config.client: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: logs
  json-content:
    enabled: true
  http:
    enabled: true

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true

spring.web.resources.add-mappings: false
